#include "z80.h"


using namespace xprocessors::cpu;


const std::vector<Z80::opcode_steps> Z80::opcodes_timing[] =
{
	// 0x00 - 0x0F
	{ NOP, FETCH }, // NOP
	{ NOP, READPC, WAIT, LD_DB_INTO_C, READPC, WAIT, LD_DB_INTO_B, FETCH }, // LD BC,nn
	{ LD_BC_INTO_WZ, WRITE_A, WRITE, NOP, FETCH }, // LD (BC),A
	{ NOP, INC_BC, NOP, FETCH }, // INC BC
	{ INC_B, FETCH }, // INC B
	{ DEC_B, FETCH }, // DEC B
	{ NOP, READPC, WAIT, LD_DB_INTO_B, FETCH }, // LD B,n
	{ RLCA, FETCH }, // RLCA
	{ EXAF, FETCH }, // EX AF,AF'
	{ LD_BC_INTO_WZ, NOP, NOP, NOP, NOP, NOP, NOP, ADD_WZ_TO_HL, FETCH }, // ADD HL,BC
	{ LD_BC_INTO_WZ, READ, WAIT, LD_DB_INTO_A, FETCH }, // LD A,(BC)
	{ NOP, DEC_BC, NOP, FETCH }, // DEC BC
	{ INC_C, FETCH }, // INC C
	{ DEC_C, FETCH }, // DEC C
	{ NOP, READPC, WAIT, LD_DB_INTO_C, FETCH }, // LD C,n
	{ RRCA, FETCH }, // RRCA

	// 0x10 - 0x1F
	{ DEC_B, READPC, WAIT, NOP, STOPZ, NOP, NOP, NOP, NOP, JR, FETCH }, // DJNZ n
	{ NOP, READPC, WAIT, LD_DB_INTO_E, READPC, WAIT, LD_DB_INTO_D, FETCH }, // LD DE,nn
	{ LD_DE_INTO_WZ, WRITE_A, WRITE, NOP, FETCH }, // LD (DE),A
	{ NOP, INC_DE, NOP, FETCH }, // INC DE
	{ INC_D, FETCH }, // INC D
	{ DEC_D, FETCH }, // DEC D
	{ NOP, READPC, WAIT, LD_DB_INTO_D, FETCH }, // LD D,n
	{ RLA, FETCH }, // RLA
	{ NOP, READPC, WAIT, NOP, NOP, NOP, NOP, NOP, JR, FETCH }, // JR n
	{ LD_DE_INTO_WZ, NOP, NOP, NOP, NOP, NOP, NOP, ADD_WZ_TO_HL, FETCH }, // ADD HL,DE
	{ LD_DE_INTO_WZ, READ, WAIT, LD_DB_INTO_A, FETCH }, // LD A,(DE)
	{ NOP, DEC_DE, NOP, FETCH }, // DEC DE
	{ INC_E, FETCH }, // INC E
	{ DEC_E, FETCH }, // DEC E
	{ NOP, READPC, WAIT, LD_DB_INTO_E, FETCH }, // LD E,n
	{ RRA, FETCH }, // RRA

	// 0x20 - 0x2F
	{ NOP, READPC, WAIT, STOPZ, NOP, NOP, NOP, NOP, JR, FETCH }, // JR NZ,n
	{ NOP, READPC, WAIT, LD_DB_INTO_L, READPC, WAIT, LD_DB_INTO_H, FETCH }, // LD HL,nn
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, LD_DB_INTO_WZH, WRITEL, WRITE, INC_WZ, WRITEH, WRITE, NOP, FETCH }, // LD (nn),HL
	{ NOP, INC_HL, NOP, FETCH }, // INC HL
	{ INC_H, FETCH }, // INC H
	{ DEC_H, FETCH }, // DEC H
	{ NOP, READPC, WAIT, LD_DB_INTO_H, FETCH }, // LD H,n
	{ DAA, FETCH }, // DAA
	{ NOP, READPC, WAIT, STOPNZ, NOP, NOP, NOP, NOP, JR, FETCH }, // JR Z,n
	{ LD_HL_INTO_WZ, NOP, NOP, NOP, NOP, NOP, NOP, ADD_WZ_TO_HL, FETCH }, // ADD HL,HL
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, LD_DB_INTO_WZH, READWR, WAIT, LD_DB_INTO_L, READWR, WAIT, LD_DB_INTO_H, FETCH }, // LD HL,(nn)
	{ NOP, DEC_HL, NOP, FETCH }, // DEC HL
	{ INC_L, FETCH }, // INC L
	{ DEC_L, FETCH }, // DEC L
	{ NOP, READPC, WAIT, LD_DB_INTO_L, FETCH }, // LD L,n
	{ CPL, FETCH }, // CPL

	// 0x30 - 0x3F
	{ NOP, READPC, WAIT, STOPC, NOP, NOP, NOP, NOP, JR, FETCH }, // JR NC,n
	{ NOP, READPC, WAIT, LD_DB_INTO_SPL, READPC, WAIT, LD_DB_INTO_SPH, FETCH }, // LD sp,nn
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, LD_DB_INTO_WZH, WRITE_A, WRITE, NOP, FETCH }, // LD (nn),A
	{ NOP, INCSP, NOP, FETCH }, // INC SP
	{ LD_HL_INTO_WZ, READ, WAIT, NOP, INC_DB, WRITE_DB, WRITE, NOP, FETCH }, // INC (HL)
	{ LD_HL_INTO_WZ, READ, WAIT, NOP, DEC_DB, WRITE_DB, WRITE, NOP, FETCH }, // DEC (HL)
	{ LD_HL_INTO_WZ, READPC, WAIT, NOP, WRITE_DB, WRITE, NOP, FETCH }, // LD (HL),n
	{ SCF, FETCH }, // SCF
	{ NOP, READPC, WAIT, STOPNC, NOP, NOP, NOP, NOP, JR, FETCH }, // JR C,n
	{ LD_SP_INTO_WZ, NOP, NOP, NOP, NOP, NOP, NOP, ADD_WZ_TO_HL, FETCH }, // ADD HL,SP
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, LD_DB_INTO_WZH, READ, WAIT, LD_DB_INTO_A, FETCH }, // LD A,(nn)
	{ NOP, DECSP, NOP, FETCH }, // DEC SP
	{ INC_A, FETCH }, // INC A
	{ DEC_A, FETCH }, // DEC A
	{ NOP, READPC, WAIT, LD_DB_INTO_A, FETCH }, // LD A,n
	{ CCF, FETCH }, // CCF

	// 0x40 - 0x4F
	{ NOP, FETCH }, // LD B,B
	{ LD_C_INTO_B, FETCH }, // LD B,C
	{ LD_D_INTO_B, FETCH }, // LD B,D
	{ LD_E_INTO_B, FETCH }, // LD B,E
	{ LD_H_INTO_B, FETCH }, // LD B,H
	{ LD_L_INTO_B, FETCH }, // LD B,L
	{ LD_HL_INTO_WZ, READ, WAIT, LD_DB_INTO_B, FETCH }, // LD B,(HL)
	{ LD_A_INTO_B, FETCH }, // LD B,A
	{ LD_B_INTO_C, FETCH }, // LD C,B
	{ NOP, FETCH }, // LD C,C
	{ LD_D_INTO_C, FETCH }, // LD C,D
	{ LD_E_INTO_C, FETCH }, // LD C,E
	{ LD_H_INTO_C, FETCH }, // LD C,H
	{ LD_L_INTO_C, FETCH }, // LD C,L
	{ LD_HL_INTO_WZ, READ, WAIT, LD_DB_INTO_C, FETCH }, // LD C,(HL)
	{ LD_A_INTO_C, FETCH }, // LD C,A

	// 0x50 - 0x5F
	{ LD_B_INTO_D, FETCH }, // LD D,B
	{ LD_C_INTO_D, FETCH }, // LD D,C
	{ NOP, FETCH }, // LD D,D
	{ LD_E_INTO_D, FETCH }, // LD D,E
	{ LD_H_INTO_D, FETCH }, // LD D,H
	{ LD_L_INTO_D, FETCH }, // LD D,L
	{ LD_HL_INTO_WZ, READ, WAIT, LD_DB_INTO_D, FETCH }, // LD D,(HL)
	{ LD_A_INTO_D, FETCH }, // LD D,A
	{ LD_B_INTO_E, FETCH }, // LD E,B
	{ LD_C_INTO_E, FETCH }, // LD E,C
	{ LD_D_INTO_E, FETCH }, // LD E,D
	{ NOP, FETCH }, // LD E,E
	{ LD_H_INTO_E, FETCH }, // LD E,H
	{ LD_L_INTO_E, FETCH }, // LD E,L
	{ LD_HL_INTO_WZ, READ, WAIT, LD_DB_INTO_E, FETCH }, // LD E,(HL)
	{ LD_A_INTO_E, FETCH }, // LD E,A

	// 0x60 - 0x6F
	{ LD_B_INTO_H, FETCH }, // LD H,B
	{ LD_C_INTO_H, FETCH }, // LD H,C
	{ LD_D_INTO_H, FETCH }, // LD H,D
	{ LD_E_INTO_H, FETCH }, // LD H,E
	{ NOP, FETCH }, // LD H,H
	{ LD_L_INTO_H, FETCH }, // LD H,L
	{ LD_HL_INTO_WZ, READ, WAIT, LD_DB_INTO_H, FETCH }, // LD H,(HL)
	{ LD_A_INTO_H, FETCH }, // LD H,A
	{ LD_B_INTO_L, FETCH }, // LD L,B
	{ LD_C_INTO_L, FETCH }, // LD L,C
	{ LD_D_INTO_L, FETCH }, // LD L,D
	{ LD_E_INTO_L, FETCH }, // LD L,E
	{ LD_H_INTO_L, FETCH }, // LD L,H
	{ NOP, FETCH }, // LD L,L
	{ LD_HL_INTO_WZ, READ, WAIT, LD_DB_INTO_L, FETCH }, // LD L,(HL)
	{ LD_A_INTO_L, FETCH }, // LD L,A

	// 0x70 - 0x7F
	{ LD_HL_INTO_WZ, WRITEB, WRITE, NOP, FETCH }, // LD (HL),B
	{ LD_HL_INTO_WZ, WRITEC, WRITE, NOP, FETCH }, // LD (HL),C
	{ LD_HL_INTO_WZ, WRITED, WRITE, NOP, FETCH }, // LD (HL),D
	{ LD_HL_INTO_WZ, WRITEE, WRITE, NOP, FETCH }, // LD (HL),E
	{ LD_HL_INTO_WZ, WRITEH, WRITE, NOP, FETCH }, // LD (HL),H
	{ LD_HL_INTO_WZ, WRITEL, WRITE, NOP, FETCH }, // LD (HL),L
	{ HALT, FETCH }, // HALT
	{ LD_HL_INTO_WZ, WRITE_A, WRITE, NOP, FETCH }, // LD (HL),A
	{ LD_B_INTO_A, FETCH }, // LD L,B
	{ LD_C_INTO_A, FETCH }, // LD L,C
	{ LD_D_INTO_A, FETCH }, // LD L,D
	{ LD_E_INTO_A, FETCH }, // LD L,E
	{ LD_H_INTO_A, FETCH }, // LD L,H
	{ LD_L_INTO_A, FETCH }, // LD L,L
	{ LD_HL_INTO_WZ, READ, WAIT, LD_DB_INTO_A, FETCH }, // LD A,(HL)
	{ NOP, FETCH }, // LD A,A

	// 0x80 - 0x8F
	{ ADD_B_TO_A, FETCH }, // ADD B
	{ ADD_C_TO_A, FETCH }, // ADD C
	{ ADD_D_TO_A, FETCH }, // ADD D
	{ ADD_E_TO_A, FETCH }, // ADD E
	{ ADD_H_TO_A, FETCH }, // ADD H
	{ ADD_L_TO_A, FETCH }, // ADD L
	{ LD_HL_INTO_WZ, READ, WAIT, ADD_DB_TO_A, FETCH }, // ADD (HL)
	{ ADD_A_TO_A, FETCH }, // ADD A
	{ ADC_B_TO_A, FETCH }, // ADC B
	{ ADC_C_TO_A, FETCH }, // ADC C
	{ ADC_D_TO_A, FETCH }, // ADC D
	{ ADC_E_TO_A, FETCH }, // ADC E
	{ ADC_H_TO_A, FETCH }, // ADC H
	{ ADC_L_TO_A, FETCH }, // ADC L
	{ LD_HL_INTO_WZ, READ, WAIT, ADC_DB_TO_A, FETCH }, // ADC (HL)
	{ ADC_A_TO_A, FETCH }, // ADC A

	// 0x90 - 0x9F
	{ SUB_B_TO_A, FETCH }, // SUB B
	{ SUB_C_TO_A, FETCH }, // SUB C
	{ SUB_D_TO_A, FETCH }, // SUB D
	{ SUB_E_TO_A, FETCH }, // SUB E
	{ SUB_H_TO_A, FETCH }, // SUB H
	{ SUB_L_TO_A, FETCH }, // SUB L
	{ LD_HL_INTO_WZ, READ, WAIT, SUB_DB_TO_A, FETCH }, // SUB (HL)
	{ SUB_A_TO_A, FETCH }, // SUB A
	{ SBC_B_TO_A, FETCH }, // SBC B
	{ SBC_C_TO_A, FETCH }, // SBC C
	{ SBC_D_TO_A, FETCH }, // SBC D
	{ SBC_E_TO_A, FETCH }, // SBC E
	{ SBC_H_TO_A, FETCH }, // SBC H
	{ SBC_L_TO_A, FETCH }, // SBC L
	{ LD_HL_INTO_WZ, READ, WAIT, SBC_DB_TO_A, FETCH }, // SBC (HL)
	{ SBC_A_TO_A, FETCH }, // SBC A

	// 0xA0 - 0xAF
	{ AND_B, FETCH }, // AND B
	{ AND_C, FETCH }, // AND C
	{ AND_D, FETCH }, // AND D
	{ AND_E, FETCH }, // AND E
	{ AND_H, FETCH }, // AND H
	{ AND_L, FETCH }, // AND L
	{ LD_HL_INTO_WZ, READ, WAIT, AND_DB, FETCH }, // AND (HL)
	{ AND_A, FETCH }, // AND A
	{ XOR_B, FETCH }, // XOR B
	{ XOR_C, FETCH }, // XOR C
	{ XOR_D, FETCH }, // XOR D
	{ XOR_E, FETCH }, // XOR E
	{ XOR_H, FETCH }, // XOR H
	{ XOR_L, FETCH }, // XOR L
	{ LD_HL_INTO_WZ, READ, WAIT, XOR_DB, FETCH }, // XOR (HL)
	{ XOR_A, FETCH }, // XOR A

	// 0xB0 - 0xBF
	{ OR_B, FETCH }, // OR B
	{ OR_C, FETCH }, // OR C
	{ OR_D, FETCH }, // OR D
	{ OR_E, FETCH }, // OR E
	{ OR_H, FETCH }, // OR H
	{ OR_L, FETCH }, // OR L
	{ LD_HL_INTO_WZ, READ, WAIT, OR_DB, FETCH }, // OR (HL)
	{ OR_A, FETCH }, // OR A
	{ CP_B, FETCH }, // CP B
	{ CP_C, FETCH }, // CP C
	{ CP_D, FETCH }, // CP D
	{ CP_E, FETCH }, // CP E
	{ CP_H, FETCH }, // CP H
	{ CP_L, FETCH }, // CP L
	{ LD_HL_INTO_WZ, READ, WAIT, CP_DB, FETCH }, // CP (HL)
	{ CP_A, FETCH }, // CP A

	// 0xC0 - 0xCF
	{ NOP, STOPZ, READSP, WAIT, FILLPCL, READSP, WAIT, FILLPCH, FETCH }, // RET NZ
	{ NOP, READSP, WAIT, LD_DB_INTO_C, READSP, WAIT, LD_DB_INTO_B, FETCH }, // POP BC
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, JPNZ, FETCH }, // JP NZ,nn
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, JP, FETCH }, // JP nn
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, STOPZ, LD_DB_INTO_WZH, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, JP_WZ, FETCH }, // CALL NZ,nn
	{ NOP, PUSH, WRITEB, WRITE, PUSH, WRITEC, WRITE, NOP, FETCH }, // PUSH BC
	{ NOP, READPC, WAIT, ADD_DB_TO_A, FETCH }, // ADD A,n
	{ NOP, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, NOP, JP_0, FETCH }, // RST 0
	{ NOP, STOPNZ, READSP, WAIT, FILLPCL, READSP, WAIT, FILLPCH, FETCH }, // RET Z
	{ NOP, READSP, WAIT, FILLPCL, READSP, WAIT, FILLPCH, FETCH }, // RET
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, JPZ, FETCH }, // JP Z,nn
	{ PREFIX_CB, FETCH_PREFIX }, // CB prefix
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, STOPNZ, LD_DB_INTO_WZH, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, JP_WZ, FETCH }, // CALL Z,nn
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, LD_DB_INTO_WZH, NOP, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, JP_WZ, FETCH }, // CALL nn
	{ NOP, READPC, WAIT, ADC_DB_TO_A, FETCH }, // ADC A,n
	{ NOP, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, NOP, JP_08, FETCH }, // RST 08

	// 0xD0 - 0xDF
	{ NOP, STOPC, READSP, WAIT, FILLPCL, READSP, WAIT, FILLPCH, FETCH }, // RET NC
	{ NOP, READSP, WAIT, LD_DB_INTO_E, READSP, WAIT, LD_DB_INTO_D, FETCH }, // POP DE
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, JPNC, FETCH }, // JP NC,nn
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, CPAWRH, OUTA, IOWRITE, NOP, FETCH }, // OUT (n),A
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, STOPC, LD_DB_INTO_WZH, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, JP_WZ, FETCH }, // CALL NC,nn
	{ NOP, PUSH, WRITED, WRITE, PUSH, WRITEE, WRITE, NOP, FETCH }, // PUSH DE
	{ NOP, READPC, WAIT, SUB_DB_TO_A, FETCH }, // SUB n
	{ NOP, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, NOP, JP_10, FETCH }, // RST 10
	{ NOP, STOPNC, READSP, WAIT, FILLPCL, READSP, WAIT, FILLPCH, FETCH }, // RET C
	{ EXX, FETCH }, // EXX
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, JPC, FETCH }, // JP C,nn
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, LD_A_INTO_WZH, READIO, WAIT, LD_DB_INTO_A, FETCH }, // IN A,(n)
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, STOPNC, LD_DB_INTO_WZH, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, JP_WZ, FETCH }, // CALL C,nn
	{ PREFIX_DD, FETCH_PREFIX }, // DD prefix
	{ NOP, READPC, WAIT, SBC_DB_TO_A, FETCH }, // SBC n
	{ NOP, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, NOP, JP_18, FETCH }, // RST 18

	// 0xE0 - 0xEF
	{ NOP, STOPPE, READSP, WAIT, FILLPCL, READSP, WAIT, FILLPCH, FETCH }, // RET PO
	{ NOP, READSP, WAIT, LD_DB_INTO_L, READSP, WAIT, LD_DB_INTO_H, FETCH }, // POP HL
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, JPPO, FETCH }, // JP PO,nn
	{ NOP, READSP, WAIT, LD_DB_INTO_WZL, READSP, WAIT, LD_DB_INTO_WZH, PUSH_H, WRITE, NOP, PUSH_L, WRITE, NOP, LD_WZ_INTO_HL, NOP, NOP, FETCH }, // EX (SP),HL
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, STOPPE, LD_DB_INTO_WZH, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, JP_WZ, FETCH }, // CALL PO,nn
	{ NOP, PUSH, WRITEH, WRITE, PUSH, WRITEL, WRITE, NOP, FETCH }, // PUSH HL
	{ NOP, READPC, WAIT, AND_DB, FETCH }, // AND n
	{ NOP, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, NOP, JP_20, FETCH }, // RST 20
	{ NOP, STOPPO, READSP, WAIT, FILLPCL, READSP, WAIT, FILLPCH, FETCH }, // RET PE
	{ JPHL, FETCH }, // JP (HL)
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, JPPE, FETCH }, // JP PE,nn
	{ EX_DE_HL, FETCH }, // EX DE,HL
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, STOPPO, LD_DB_INTO_WZH, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, JP_WZ, FETCH }, // CALL PE,nn
	{ PREFIX_ED, FETCH_PREFIX }, // ED prefix
	{ NOP, READPC, WAIT, XOR_DB, FETCH }, // XOR n
	{ NOP, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, NOP, JP_28, FETCH }, // RST 28

	// 0xF0 - 0xFF
	{ NOP, STOPM, READSP, WAIT, FILLPCL, READSP, WAIT, FILLPCH, FETCH }, // RET P
	{ NOP, READSP, WAIT, LD_DB_INTO_F, READSP, WAIT, LD_DB_INTO_A, FETCH }, // POP AF
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, JPP, FETCH }, // JP P,nn
	{ DI, FETCH }, // DI
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, STOPM, LD_DB_INTO_WZH, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, JP_WZ, FETCH }, // CALL P,nn
	{ NOP, PUSH, WRITE_A, WRITE, PUSH, WRITEF, WRITE, NOP, FETCH }, // PUSH AF
	{ NOP, READPC, WAIT, OR_DB, FETCH }, // OR n
	{ NOP, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, NOP, JP_30, FETCH }, // RST 30
	{ NOP, STOPP, READSP, WAIT, FILLPCL, READSP, WAIT, FILLPCH, FETCH }, // RET M
	{ LD_HL_INTO_WZ, LD_WZ_INTO_SP, NOP, FETCH }, // LD SP,HL
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, JPM, FETCH }, // JP M,nn
	{ EI, FETCH }, // EI
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, STOPP, LD_DB_INTO_WZH, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, JP_WZ, FETCH }, // CALL M,nn
	{ PREFIX_FD, FETCH_PREFIX }, // FD prefix
	{ NOP, READPC, WAIT, CP_DB, FETCH }, // CP n
	{ NOP, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, NOP, JP_38, FETCH }, // RST 38

	// 0x100 -
	{ DI, NOP, NOP, NOP, NOP, NOP, NOP, NOP, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, NOP, JP_38, FETCH }, // Interrup Mode 1
	{ DI, READIO, WAIT, LD_DB_INTO_WZL, NOP, LD_I_INTO_WZH, NOP, NOP, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, NOP, NOP, READWR, WAIT, FILLPCL, READWR, WAIT, FILLPCH, FETCH },
	{ DI, READIO, WAIT, LD_DB_INTO_WZL, NOP, PUSH_PCH, WRITE, NOP, PUSH_PCL, WRITE, FETCHWZL }
};

const std::vector<Z80::opcode_steps> Z80::opcodes_timing_fd[] =
{
	// 0x00 - 0x0F
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ INC_B, FETCH }, // INC B
	{ DEC_B, FETCH }, // DEC B
	{ NOP, READPC, WAIT, LD_DB_INTO_B, FETCH }, // LD B,n
	{ ERROR },
	{ ERROR },
	{ LD_BC_INTO_WZ, NOP, NOP, NOP, NOP, NOP, NOP, ADD_WZ_TO_IY, FETCH }, // ADD IY,BC
	{ ERROR },
	{ ERROR },
	{ INC_C, FETCH }, // INC C
	{ DEC_C, FETCH }, // DEC C
	{ NOP, READPC, WAIT, LD_DB_INTO_C, FETCH }, // LD C,n
	{ ERROR },

	// 0x10 - 0x1F
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ INC_D, FETCH }, // INC D
	{ DEC_D, FETCH }, // DEC D
	{ NOP, READPC, WAIT, LD_DB_INTO_D, FETCH }, // LD D,n
	{ ERROR },
	{ ERROR },
	{ LD_DE_INTO_WZ, NOP, NOP, NOP, NOP, NOP, NOP, ADD_WZ_TO_IY, FETCH }, // ADD IY,DE
	{ ERROR },
	{ ERROR },
	{ INC_E, FETCH }, // INC E
	{ DEC_E, FETCH }, // DEC E
	{ NOP, READPC, WAIT, LD_DB_INTO_E, FETCH }, // LD E,n
	{ ERROR },

	// 0x20 - 0x2F
	{ ERROR },
	{ NOP, READPC, WAIT, LD_DB_INTO_IYL, READPC, WAIT, LD_DB_INTO_IYH, FETCH }, // LD IY,nn
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, LD_DB_INTO_WZH, WRITEIYL, WRITE, INC_WZ, WRITEIYH, WRITE, NOP, FETCH }, // LD (nn),IY
	{ NOP, INC_IY, NOP, FETCH }, // INC IY
	{ INC_IYH, FETCH }, // INC IYh
	{ DEC_IYH, FETCH }, // DEC IYh
	{ NOP, READPC, WAIT, LD_DB_INTO_IYH, FETCH }, // LD IYh,n
	{ ERROR },
	{ ERROR },
	{ LD_IY_INTO_WZ, NOP, NOP, NOP, NOP, NOP, NOP, ADD_WZ_TO_IY, FETCH }, // ADD IY,IY
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, LD_DB_INTO_WZH, READWR, WAIT, LD_DB_INTO_IYL, READWR, WAIT, LD_DB_INTO_IYH, FETCH }, // LD IY,(nn)
	{ NOP, DEC_IY, NOP, FETCH }, // DEC IY
	{ INC_IYL, FETCH }, // INC IYl
	{ DEC_IYL, FETCH }, // DEC IYl
	{ NOP, READPC, WAIT, LD_DB_INTO_IYL, FETCH }, // LD IYL,n
	{ ERROR },

	// 0x30 - 0x3F
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ, ADD_DB_TO_WZ, READ, WAIT, NOP, INC_DB, WRITE_DB, WRITE, NOP, NOP, NOP, NOP, NOP, FETCH }, // INC (IY+d)
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ, ADD_DB_TO_WZ, READ, WAIT, NOP, DEC_DB, WRITE_DB, WRITE, NOP, NOP, NOP, NOP, NOP, FETCH }, // DEC (IY+d)
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, READPC, WAIT, NOP, NOP, WRITE_DB, WRITE, NOP, FETCH }, // LD (IY+d),n
	{ ERROR },
	{ ERROR },
	{ LD_SP_INTO_WZ, NOP, NOP, NOP, NOP, NOP, NOP, ADD_WZ_TO_IY, FETCH }, // ADD IY,SP
	{ ERROR },
	{ ERROR },
	{ INC_A, FETCH }, // INC A
	{ DEC_A, FETCH }, // DEC A
	{ NOP, READPC, WAIT, LD_DB_INTO_A, FETCH }, // LD A,n
	{ ERROR },

	// 0x40 - 0x4F
	{ NOP, FETCH }, // LD B,B
	{ LD_C_INTO_B, FETCH }, // LD B,C
	{ LD_D_INTO_B, FETCH }, // LD B,D
	{ LD_E_INTO_B, FETCH }, // LD B,E
	{ LD_IYH_INTO_B, FETCH }, // LD B,IYh
	{ LD_IYL_INTO_B, FETCH }, // LD B,IYl
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_B, FETCH }, // LD B,(IY+d)
	{ LD_A_INTO_B, FETCH }, // LD B,A
	{ LD_B_INTO_C, FETCH }, // LD C,B
	{ NOP, FETCH }, // LD C,C
	{ LD_D_INTO_C, FETCH }, // LD C,D
	{ LD_E_INTO_C, FETCH }, // LD C,E
	{ LD_IYH_INTO_C, FETCH }, // LD C,IYh
	{ LD_IYL_INTO_C, FETCH }, // LD C,IYl
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_C, FETCH }, // LD C,(IY+d)
	{ LD_A_INTO_C, FETCH }, // LD C,A

	// 0x50 - 0x5F
	{ LD_B_INTO_D, FETCH }, // LD D,B
	{ LD_C_INTO_D, FETCH }, // LD D,C
	{ NOP, FETCH }, // LD D,D
	{ LD_E_INTO_D, FETCH }, // LD D,E
	{ LD_IYH_INTO_D, FETCH }, // LD D,IYh
	{ LD_IYL_INTO_D, FETCH }, // LD D,IYl
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_D, FETCH }, // LD D,(IY+d)
	{ LD_A_INTO_D, FETCH }, // LD D,A
	{ LD_B_INTO_E, FETCH }, // LD E,B
	{ LD_C_INTO_E, FETCH }, // LD E,C
	{ LD_D_INTO_E, FETCH }, // LD E,D
	{ NOP, FETCH }, // LD E,E
	{ LD_IYH_INTO_E, FETCH }, // LD E,IYh
	{ LD_IYL_INTO_E, FETCH }, // LD E,IYl
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_E, FETCH }, // LD E,(IY+d)
	{ LD_A_INTO_E, FETCH }, // LD E,A

	// 0x60 - 0x6F
	{ LD_B_INTO_IYH, FETCH }, // LD IYH,B
	{ LD_C_INTO_IYH, FETCH }, // LD IYH,C
	{ LD_D_INTO_IYH, FETCH }, // LD IYH,D
	{ LD_E_INTO_IYH, FETCH }, // LD IYH,E
	{ NOP, FETCH }, // LD IYH,IYH
	{ LD_IYL_INTO_IYH, FETCH }, // LD IYH,IYL
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_H, FETCH }, // LD H,(IY+d)
	{ LD_A_INTO_IYH, FETCH }, // LD IYH,A
	{ LD_B_INTO_IYL, FETCH }, // LD IYL,B
	{ LD_C_INTO_IYL, FETCH }, // LD IYL,C
	{ LD_D_INTO_IYL, FETCH }, // LD IYL,D
	{ LD_E_INTO_IYL, FETCH }, // LD IYL,E
	{ LD_IYH_INTO_IYL, FETCH }, // LD IYL,IYH
	{ NOP, FETCH }, // LD IYL,IYL
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_L, FETCH }, // LD L,(IY+d)
	{ LD_A_INTO_IYL, FETCH }, // LD IYL,A

	// 0x70 - 0x7F
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITEB, WRITE, NOP, FETCH }, // LD (IY+d),B
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITEC, WRITE, NOP, FETCH }, // LD (IY+d),C
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITED, WRITE, NOP, FETCH }, // LD (IY+d),D
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITEE, WRITE, NOP, FETCH }, // LD (IY+d),E
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITEH, WRITE, NOP, FETCH }, // LD (IY+d),H
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITEL, WRITE, NOP, FETCH }, // LD (IY+d),L
	{ ERROR },
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITE_A, WRITE, NOP, FETCH }, // LD (IY+d),A
	{ LD_B_INTO_A, FETCH }, // LD A,B
	{ LD_C_INTO_A, FETCH }, // LD A,C
	{ LD_D_INTO_A, FETCH }, // LD A,D
	{ LD_E_INTO_A, FETCH }, // LD A,E
	{ LD_IYH_INTO_A, FETCH }, // LD A,IYh
	{ LD_IYL_INTO_A, FETCH }, // LD A,IYl
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_A, FETCH }, // LD A,(IY+d)
	{ NOP, FETCH }, // LD A,A

	// 0x80 - 0x8F
	{ ADD_B_TO_A, FETCH }, // ADD B
	{ ADD_C_TO_A, FETCH }, // ADD C
	{ ADD_D_TO_A, FETCH }, // ADD D
	{ ADD_E_TO_A, FETCH }, // ADD E
	{ ADD_IYH_TO_A, FETCH }, // ADD IYh
	{ ADD_IYL_TO_A, FETCH }, // ADD IYl
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, ADD_DB_TO_A, FETCH }, // ADD A,(IY+d)
	{ ADD_A_TO_A, FETCH }, // ADD A
	{ ADC_B_TO_A, FETCH }, // ADC B
	{ ADC_C_TO_A, FETCH }, // ADC C
	{ ADC_D_TO_A, FETCH }, // ADC D
	{ ADC_E_TO_A, FETCH }, // ADC E
	{ ADC_IYH_TO_A, FETCH }, // ADC IYh
	{ ADC_IYL_TO_A, FETCH }, // ADC IYl
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, ADC_DB_TO_A, FETCH }, // ADC A,(IY+d)
	{ ADC_A_TO_A, FETCH }, // ADC A

	// 0x90 - 0x9F
	{ SUB_B_TO_A, FETCH }, // SUB B
	{ SUB_C_TO_A, FETCH }, // SUB C
	{ SUB_D_TO_A, FETCH }, // SUB D
	{ SUB_E_TO_A, FETCH }, // SUB E
	{ SUB_IYH_TO_A, FETCH }, // SUB IYh
	{ SUB_IYL_TO_A, FETCH }, // SUB IYl
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, SUB_DB_TO_A, FETCH }, // SUB (IY+d)
	{ SUB_A_TO_A, FETCH }, // SUB A
	{ SBC_B_TO_A, FETCH }, // SBC B
	{ SBC_C_TO_A, FETCH }, // SBC C
	{ SBC_D_TO_A, FETCH }, // SBC D
	{ SBC_E_TO_A, FETCH }, // SBC E
	{ SBC_IYH_TO_A, FETCH }, // SBC IYh
	{ SBC_IYL_TO_A, FETCH }, // SBC IYl
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, SBC_DB_TO_A, FETCH }, // SBC (IY+d)
	{ SBC_A_TO_A, FETCH }, // SBC A

	// 0xA0 - 0xAF
	{ AND_B, FETCH }, // AND B
	{ AND_C, FETCH }, // AND C
	{ AND_D, FETCH }, // AND D
	{ AND_E, FETCH }, // AND E
	{ AND_IYH, FETCH }, // AND IYh
	{ AND_IYL, FETCH }, // AND IYl
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, AND_DB, FETCH }, // AND (IY+d)
	{ AND_A, FETCH }, // AND A
	{ XOR_B, FETCH }, // XOR B
	{ XOR_C, FETCH }, // XOR C
	{ XOR_D, FETCH }, // XOR D
	{ XOR_E, FETCH }, // XOR E
	{ XOR_IYH, FETCH }, // XOR IYh
	{ XOR_IYL, FETCH }, // XOR IYl
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, XOR_DB, FETCH }, // XOR (IY+d)
	{ XOR_A, FETCH }, // XOR A

	// 0xB0 - 0xBF
	{ OR_B, FETCH }, // OR B
	{ OR_C, FETCH }, // OR C
	{ OR_D, FETCH }, // OR D
	{ OR_E, FETCH }, // OR E
	{ OR_IYH, FETCH }, // OR IYh
	{ OR_IYL, FETCH }, // OR IYl
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, OR_DB, FETCH }, // OR (IY+d)
	{ OR_A, FETCH }, // OR A
	{ CP_B, FETCH }, // CP B
	{ CP_C, FETCH }, // CP C
	{ CP_D, FETCH }, // CP D
	{ CP_E, FETCH }, // CP E
	{ CP_IYH, FETCH }, // CP IYh
	{ CP_IYL, FETCH }, // CP IYl
	{ NOP, READPC, WAIT, LD_IY_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, CP_DB, FETCH }, // CP (IY+d)
	{ CP_A, FETCH }, // CP A

	// 0xC0 - 0xCF
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{ PREFIX_DDCB, READPC, WAIT, LD_IY_INTO_WZ, ADD_DB_TO_WZ, READPC, WAIT, DECODE },
	{},
	{},
	{},
	{},

	// 0xD0 - 0xDF
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},

	// 0xE0 - 0xEF
	{},
	{ NOP, READSP, WAIT, LD_DB_INTO_IYL, READSP, WAIT, LD_DB_INTO_IYH, FETCH }, // POP IY
	{},
	{ NOP, READSP, WAIT, LD_DB_INTO_WZL, READSP, WAIT, LD_DB_INTO_WZH, PUSH_IYH, WRITE, NOP, PUSH_IYL, WRITE, NOP, LD_WZ_INTO_IY, NOP, NOP, FETCH }, // EX (SP),IY
	{},
	{ NOP, PUSH, WRITEIYH, WRITE, PUSH, WRITEIYL, WRITE, NOP, FETCH }, // PUSH IY
	{},
	{},
	{},
	{ JPIY, FETCH }, // JP (IY)
	{},
	{},
	{},
	{},
	{},
	{},

	// 0xF0 - 0xFF
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{ LD_IY_INTO_WZ, LD_WZ_INTO_SP, NOP, FETCH }, // LD SP,IY
	{},
	{},
	{},
	{},
	{},
	{}
};
