#include "z80.h"

using namespace xprocessors::cpu;

const std::vector<Z80::opcode_steps> Z80::opcodes_timing_dd[] =
{
	// 0x00 - 0x0F
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ INC_B, FETCH }, // INC B
	{ DEC_B, FETCH }, // DEC B
	{ NOP, READPC, WAIT, LD_DB_INTO_B, FETCH }, // LD B,n
	{ ERROR },
	{ ERROR },
	{ LD_BC_INTO_WZ, NOP, NOP, NOP, NOP, NOP, NOP, ADD_WZ_TO_IX, FETCH }, // ADD IX,BC
	{ ERROR },
	{ ERROR },
	{ INC_C, FETCH }, // INC C
	{ DEC_C, FETCH }, // DEC C
	{ NOP, READPC, WAIT, LD_DB_INTO_C, FETCH }, // LD C,n
	{ ERROR },

	// 0x10 - 0x1F
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ INC_D, FETCH }, // INC D
	{ DEC_D, FETCH }, // DEC D
	{ NOP, READPC, WAIT, LD_DB_INTO_D, FETCH }, // LD D,n
	{ ERROR },
	{ ERROR },
	{ LD_DE_INTO_WZ, NOP, NOP, NOP, NOP, NOP, NOP, ADD_WZ_TO_IX, FETCH }, // ADD IX,DE
	{ ERROR },
	{ ERROR },
	{ INC_E, FETCH }, // INC E
	{ DEC_E, FETCH }, // DEC E
	{ NOP, READPC, WAIT, LD_DB_INTO_E, FETCH }, // LD E,n
	{ ERROR },

	// 0x20 - 0x2F
	{ ERROR },
	{ NOP, READPC, WAIT, LD_DB_INTO_IXL, READPC, WAIT, LD_DB_INTO_IXH, FETCH }, // LD IX,nn
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, LD_DB_INTO_WZH, WRITEIXL, WRITE, INC_WZ, WRITEIXH, WRITE, NOP, FETCH }, // LD (nn),IX
	{ NOP, INC_IX, NOP, FETCH }, // INC IX
	{ INC_IXH, FETCH }, // INC IXh
	{ DEC_IXH, FETCH }, // DEC IXh
	{ NOP, READPC, WAIT, LD_DB_INTO_IXH, FETCH }, // LD IXh,n
	{ ERROR },
	{ ERROR },
	{ LD_IX_INTO_WZ, NOP, NOP, NOP, NOP, NOP, NOP, ADD_WZ_TO_IX, FETCH }, // ADD IX,IX
	{ NOP, READPC, WAIT, LD_DB_INTO_WZL, READPC, WAIT, LD_DB_INTO_WZH, READWR, WAIT, LD_DB_INTO_IXL, READWR, WAIT, LD_DB_INTO_IXH, FETCH }, // LD IX,(nn)
	{ NOP, DEC_IX, NOP, FETCH }, // DEC IX
	{ INC_IXL, FETCH }, // INC IXl
	{ DEC_IXL, FETCH }, // DEC IXl
	{ NOP, READPC, WAIT, LD_DB_INTO_IXL, FETCH }, // LD IXl,n
	{ ERROR },

	// 0x30 - 0x3F
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ, ADD_DB_TO_WZ, READ, WAIT, NOP, INC_DB, WRITE_DB, WRITE, NOP, NOP, NOP, NOP, NOP, FETCH }, // INC (IX+d)
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ, ADD_DB_TO_WZ, READ, WAIT, NOP, DEC_DB, WRITE_DB, WRITE, NOP, NOP, NOP, NOP, NOP, FETCH }, // DEC (IX+d)
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, READPC, WAIT, NOP, NOP, WRITE_DB, WRITE, NOP, FETCH }, // LD (IX+d),n
	{ ERROR },
	{ ERROR },
	{ LD_SP_INTO_WZ, NOP, NOP, NOP, NOP, NOP, NOP, ADD_WZ_TO_IX, FETCH }, // ADD IX,SP
	{ ERROR },
	{ ERROR },
	{ INC_A, FETCH }, // INC A
	{ DEC_A, FETCH }, // DEC A
	{ NOP, READPC, WAIT, LD_DB_INTO_A, FETCH }, // LD A,n
	{ ERROR },

	// 0x40 - 0x4F
	{ NOP, FETCH }, // LD B,B
	{ LD_C_INTO_B, FETCH }, // LD B,C
	{ LD_D_INTO_B, FETCH }, // LD B,D
	{ LD_E_INTO_B, FETCH }, // LD B,E
	{ LD_IXH_INTO_B, FETCH }, // LD B,IXh
	{ LD_IXL_INTO_B, FETCH }, // LD B,IXl
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_B, FETCH }, // LD B,(IX+d)
	{ LD_A_INTO_B, FETCH }, // LD B,A
	{ LD_B_INTO_C, FETCH }, // LD C,B
	{ NOP, FETCH }, // LD C,C
	{ LD_D_INTO_C, FETCH }, // LD C,D
	{ LD_E_INTO_C, FETCH }, // LD C,E
	{ LD_IXH_INTO_C, FETCH }, // LD C,IXh
	{ LD_IXL_INTO_C, FETCH }, // LD C,IXl
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_C, FETCH }, // LD C,(IX+d)
	{ LD_A_INTO_C, FETCH }, // LD C,A

	// 0x50 - 0x5F
	{ LD_B_INTO_D, FETCH }, // LD D,B
	{ LD_C_INTO_D, FETCH }, // LD D,C
	{ NOP, FETCH }, // LD D,D
	{ LD_E_INTO_D, FETCH }, // LD D,E
	{ LD_IXH_INTO_D, FETCH }, // LD D,IXh
	{ LD_IXL_INTO_D, FETCH }, // LD D,IXl
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_D, FETCH }, // LD D,(IX+d)
	{ LD_A_INTO_D, FETCH }, // LD D,A
	{ LD_B_INTO_E, FETCH }, // LD E,B
	{ LD_C_INTO_E, FETCH }, // LD E,C
	{ LD_D_INTO_E, FETCH }, // LD E,D
	{ NOP, FETCH }, // LD E,E
	{ LD_IXH_INTO_E, FETCH }, // LD E,IXh
	{ LD_IXL_INTO_E, FETCH }, // LD E,IXl
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_E, FETCH }, // LD E,(IX+d)
	{ LD_A_INTO_E, FETCH }, // LD E,A

	// 0x60 - 0x6F
	{ LD_B_INTO_IXH, FETCH }, // LD IXH,B
	{ LD_C_INTO_IXH, FETCH }, // LD IXH,C
	{ LD_D_INTO_IXH, FETCH }, // LD IXH,D
	{ LD_E_INTO_IXH, FETCH }, // LD IXH,E
	{ NOP, FETCH }, // LD IXH,IXH
	{ LD_IXL_INTO_IXH, FETCH }, // LD IXH,IXL
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_H, FETCH }, // LD H,(IX+d)
	{ LD_A_INTO_IXH, FETCH }, // LD IXH,A
	{ LD_B_INTO_IXL, FETCH }, // LD IXL,B
	{ LD_C_INTO_IXL, FETCH }, // LD IXL,C
	{ LD_D_INTO_IXL, FETCH }, // LD IXL,D
	{ LD_E_INTO_IXL, FETCH }, // LD IXL,E
	{ LD_IXH_INTO_IXL, FETCH }, // LD IXL,IXH
	{ NOP, FETCH }, // LD IXL,IXL
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_L, FETCH }, // LD L,(IX+d)
	{ LD_A_INTO_IXL, FETCH }, // LD IXL,A

	// 0x70 - 0x7F
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITEB, WRITE, NOP, FETCH }, // LD (IX+d),B
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITEC, WRITE, NOP, FETCH }, // LD (IX+d),C
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITED, WRITE, NOP, FETCH }, // LD (IX+d),D
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITEE, WRITE, NOP, FETCH }, // LD (IX+d),E
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITEH, WRITE, NOP, FETCH }, // LD (IX+d),H
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITEL, WRITE, NOP, FETCH }, // LD (IX+d),L
	{ ERROR },
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, WRITE_A, WRITE, NOP, FETCH }, // LD (IX+d),A
	{ LD_B_INTO_A, FETCH }, // LD A,B
	{ LD_C_INTO_A, FETCH }, // LD A,C
	{ LD_D_INTO_A, FETCH }, // LD A,D
	{ LD_E_INTO_A, FETCH }, // LD A,E
	{ LD_IXH_INTO_A, FETCH }, // LD A,IXh
	{ LD_IXL_INTO_A, FETCH }, // LD A,IXl
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, LD_DB_INTO_A, FETCH }, // LD A,(IX+d)
	{ NOP, FETCH }, // LD A,A

	// 0x80 - 0x8F
	{ ADD_B_TO_A, FETCH }, // ADD B
	{ ADD_C_TO_A, FETCH }, // ADD C
	{ ADD_D_TO_A, FETCH }, // ADD D
	{ ADD_E_TO_A, FETCH }, // ADD E
	{ ADD_IXH_TO_A, FETCH }, // ADD IXh
	{ ADD_IXL_TO_A, FETCH }, // ADD IXl
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, ADD_DB_TO_A, FETCH }, // ADD A,(IX+d)
	{ ADD_A_TO_A, FETCH }, // ADD A
	{ ADC_B_TO_A, FETCH }, // ADC B
	{ ADC_C_TO_A, FETCH }, // ADC C
	{ ADC_D_TO_A, FETCH }, // ADC D
	{ ADC_E_TO_A, FETCH }, // ADC E
	{ ADC_IXH_TO_A, FETCH }, // ADC IXh
	{ ADC_IXL_TO_A, FETCH }, // ADC IXl
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, ADC_DB_TO_A, FETCH }, // ADC A,(IX+d)
	{ ADC_A_TO_A, FETCH }, // ADC A

	// 0x90 - 0x9F
	{ SUB_B_TO_A, FETCH }, // SUB B
	{ SUB_C_TO_A, FETCH }, // SUB C
	{ SUB_D_TO_A, FETCH }, // SUB D
	{ SUB_E_TO_A, FETCH }, // SUB E
	{ SUB_IXH_TO_A, FETCH }, // SUB IXh
	{ SUB_IXL_TO_A, FETCH }, // SUB IXl
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, SUB_DB_TO_A, FETCH }, // SUB A,(IX+d)
	{ SUB_A_TO_A, FETCH }, // SUB A
	{ SBC_B_TO_A, FETCH }, // SBC B
	{ SBC_C_TO_A, FETCH }, // SBC C
	{ SBC_D_TO_A, FETCH }, // SBC D
	{ SBC_E_TO_A, FETCH }, // SBC E
	{ SBC_IXH_TO_A, FETCH }, // SBC IXh
	{ SBC_IXL_TO_A, FETCH }, // SBC IXl
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, SBC_DB_TO_A, FETCH }, // SBC A,(IX+d)
	{ SBC_A_TO_A, FETCH }, // SBC A

	// 0xA0 - 0xAF
	{ AND_B, FETCH }, // AND B
	{ AND_C, FETCH }, // AND C
	{ AND_D, FETCH }, // AND D
	{ AND_E, FETCH }, // AND E
	{ AND_IXH, FETCH }, // AND IXh
	{ AND_IXL, FETCH }, // AND IXl
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, AND_DB, FETCH }, // AND (IX+d)
	{ AND_A, FETCH }, // AND A
	{ XOR_B, FETCH }, // XOR B
	{ XOR_C, FETCH }, // XOR C
	{ XOR_D, FETCH }, // XOR D
	{ XOR_E, FETCH }, // XOR E
	{ XOR_IXH, FETCH }, // XOR IXh
	{ XOR_IXL, FETCH }, // XOR IXl
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, XOR_DB, FETCH }, // XOR (IX+d)
	{ XOR_A, FETCH }, // XOR A

	// 0xB0 - 0xBF
	{ OR_B, FETCH }, // OR B
	{ OR_C, FETCH }, // OR C
	{ OR_D, FETCH }, // OR D
	{ OR_E, FETCH }, // OR E
	{ OR_IXH, FETCH }, // OR IXh
	{ OR_IXL, FETCH }, // OR IXl
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ , ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, OR_DB, FETCH }, // OR (IX+d)
	{ OR_A, FETCH }, // OR A
	{ CP_B, FETCH }, // CP B
	{ CP_C, FETCH }, // CP C
	{ CP_D, FETCH }, // CP D
	{ CP_E, FETCH }, // CP E
	{ CP_IXH, FETCH }, // CP IXh
	{ CP_IXL, FETCH }, // CP IXl
	{ NOP, READPC, WAIT, LD_IX_INTO_WZ, ADD_DB_TO_WZ, NOP, NOP, NOP, NOP, READ, WAIT, CP_DB, FETCH }, // CP (IX+d)
	{ CP_A, FETCH }, // CP A

	// 0xC0 - 0xCF
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ PREFIX_DDCB, READPC, WAIT, LD_IX_INTO_WZ, ADD_DB_TO_WZ, READPC, WAIT, DECODE },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },

	// 0xD0 - 0xDF
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },

	// 0xE0 - 0xEF
	{ ERROR },
	{ NOP, READSP, WAIT, LD_DB_INTO_IXL, READSP, WAIT, LD_DB_INTO_IXH, FETCH }, // POP IX
	{ ERROR },
	{ NOP, READSP, WAIT, LD_DB_INTO_WZL, READSP, WAIT, LD_DB_INTO_WZH, PUSH_IXH, WRITE, NOP, PUSH_IXL, WRITE, NOP, LD_WZ_INTO_IX, NOP, NOP, FETCH }, // EX (SP),IX
	{ ERROR },
	{ NOP, PUSH, WRITEIXH, WRITE, PUSH, WRITEIXL, WRITE, NOP, FETCH }, // PUSH IX
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ JPIX, FETCH }, // JP (IX)
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },

	// 0xF0 - 0xFF
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ LD_IX_INTO_WZ, LD_WZ_INTO_SP, NOP, FETCH }, // LD SP,IX
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
	{ ERROR },
};

const std::vector<Z80::opcode_steps> Z80::opcodes_timing_ddcb[] =
{
	// 0x00 - 0x0F
	{ NOP, READ, WAIT, NOP, RLC_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // RLC (IX+d), B
	{ NOP, READ, WAIT, NOP, RLC_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // RLC (IX+d), C
	{ NOP, READ, WAIT, NOP, RLC_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // RLC (IX+d), D
	{ NOP, READ, WAIT, NOP, RLC_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // RLC (IX+d), E
	{ NOP, READ, WAIT, NOP, RLC_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // RLC (IX+d), H
	{ NOP, READ, WAIT, NOP, RLC_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // RLC (IX+d), L
	{ NOP, READ, WAIT, NOP, RLC_DB, WRITE_DB, WRITE, NOP, FETCH }, // RLC (IX+d)
	{ NOP, READ, WAIT, NOP, RLC_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // RLC (IX+d), A
	{ NOP, READ, WAIT, NOP, RRC_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // RRC (IX+d), B
	{ NOP, READ, WAIT, NOP, RRC_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // RRC (IX+d), C
	{ NOP, READ, WAIT, NOP, RRC_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // RRC (IX+d), D
	{ NOP, READ, WAIT, NOP, RRC_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // RRC (IX+d), E
	{ NOP, READ, WAIT, NOP, RRC_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // RRC (IX+d), H
	{ NOP, READ, WAIT, NOP, RRC_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // RRC (IX+d), L
	{ NOP, READ, WAIT, NOP, RRC_DB, WRITE_DB, WRITE, NOP, FETCH }, // RRC (IX+d)
	{ NOP, READ, WAIT, NOP, RRC_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // RRC (IX+d), A

	// 0x10 - 0x1F
	{ NOP, READ, WAIT, NOP, RL_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // RL (IX+d), B
	{ NOP, READ, WAIT, NOP, RL_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // RL (IX+d), C
	{ NOP, READ, WAIT, NOP, RL_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // RL (IX+d), D
	{ NOP, READ, WAIT, NOP, RL_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // RL (IX+d), E
	{ NOP, READ, WAIT, NOP, RL_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // RL (IX+d), H
	{ NOP, READ, WAIT, NOP, RL_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // RL (IX+d), L
	{ NOP, READ, WAIT, NOP, RL_DB, WRITE_DB, WRITE, NOP, FETCH }, // RL (IX+d)
	{ NOP, READ, WAIT, NOP, RL_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // RL (IX+d), A
	{ NOP, READ, WAIT, NOP, RR_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // RR (IX+d), B
	{ NOP, READ, WAIT, NOP, RR_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // RR (IX+d), C
	{ NOP, READ, WAIT, NOP, RR_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // RR (IX+d), D
	{ NOP, READ, WAIT, NOP, RR_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // RR (IX+d), E
	{ NOP, READ, WAIT, NOP, RR_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // RR (IX+d), H
	{ NOP, READ, WAIT, NOP, RR_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // RR (IX+d), L
	{ NOP, READ, WAIT, NOP, RR_DB, WRITE_DB, WRITE, NOP, FETCH }, // RR (IX+d)
	{ NOP, READ, WAIT, NOP, RR_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // RR (IX+d), A

	// 0x20 - 0x2F
	{ NOP, READ, WAIT, NOP, SLA_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // SLA (IX+d), B
	{ NOP, READ, WAIT, NOP, SLA_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // SLA (IX+d), C
	{ NOP, READ, WAIT, NOP, SLA_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // SLA (IX+d), D
	{ NOP, READ, WAIT, NOP, SLA_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // SLA (IX+d), E
	{ NOP, READ, WAIT, NOP, SLA_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // SLA (IX+d), H
	{ NOP, READ, WAIT, NOP, SLA_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // SLA (IX+d), L
	{ NOP, READ, WAIT, NOP, SLA_DB, WRITE_DB, WRITE, NOP, FETCH }, // SLA (IX+d)
	{ NOP, READ, WAIT, NOP, SLA_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // SLA (IX+d), A
	{ NOP, READ, WAIT, NOP, SRA_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // SRA (IX+d), B
	{ NOP, READ, WAIT, NOP, SRA_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // SRA (IX+d), C
	{ NOP, READ, WAIT, NOP, SRA_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // SRA (IX+d), D
	{ NOP, READ, WAIT, NOP, SRA_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // SRA (IX+d), E
	{ NOP, READ, WAIT, NOP, SRA_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // SRA (IX+d), H
	{ NOP, READ, WAIT, NOP, SRA_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // SRA (IX+d), L
	{ NOP, READ, WAIT, NOP, SRA_DB, WRITE_DB, WRITE, NOP, FETCH }, // SRA (IX+d)
	{ NOP, READ, WAIT, NOP, SRA_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // SRA (IX+d), A

	// 0x30 - 0x3F
	{ NOP, READ, WAIT, NOP, SLL_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // SLL (IX+d), B
	{ NOP, READ, WAIT, NOP, SLL_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // SLL (IX+d), C
	{ NOP, READ, WAIT, NOP, SLL_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // SLL (IX+d), D
	{ NOP, READ, WAIT, NOP, SLL_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // SLL (IX+d), E
	{ NOP, READ, WAIT, NOP, SLL_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // SLL (IX+d), H
	{ NOP, READ, WAIT, NOP, SLL_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // SLL (IX+d), L
	{ NOP, READ, WAIT, NOP, SLL_DB, WRITE_DB, WRITE, NOP, FETCH }, // SLL (IX+d)
	{ NOP, READ, WAIT, NOP, SLL_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // SLL (IX+d), A
	{ NOP, READ, WAIT, NOP, SRL_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // SRL (IX+d), B
	{ NOP, READ, WAIT, NOP, SRL_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // SRL (IX+d), C
	{ NOP, READ, WAIT, NOP, SRL_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // SRL (IX+d), D
	{ NOP, READ, WAIT, NOP, SRL_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // SRL (IX+d), E
	{ NOP, READ, WAIT, NOP, SRL_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // SRL (IX+d), H
	{ NOP, READ, WAIT, NOP, SRL_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // SRL (IX+d), L
	{ NOP, READ, WAIT, NOP, SRL_DB, WRITE_DB, WRITE, NOP, FETCH }, // SRL (IX+d)
	{ NOP, READ, WAIT, NOP, SRL_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // SRL (IX+d), A

	// 0x40 - 0x4F
	{ NOP, READ, WAIT, NOP, BIT0_DB, FETCH }, // BIT 0,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT0_DB, FETCH }, // BIT 0,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT0_DB, FETCH }, // BIT 0,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT0_DB, FETCH }, // BIT 0,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT0_DB, FETCH }, // BIT 0,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT0_DB, FETCH }, // BIT 0,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT0_DB, FETCH }, // BIT 0,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT0_DB, FETCH }, // BIT 0,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT1_DB, FETCH }, // BIT 1,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT1_DB, FETCH }, // BIT 1,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT1_DB, FETCH }, // BIT 1,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT1_DB, FETCH }, // BIT 1,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT1_DB, FETCH }, // BIT 1,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT1_DB, FETCH }, // BIT 1,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT1_DB, FETCH }, // BIT 1,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT1_DB, FETCH }, // BIT 1,(IX+d)

	// 0x50 - 0x5F
	{ NOP, READ, WAIT, NOP, BIT2_DB, FETCH }, // BIT 2,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT2_DB, FETCH }, // BIT 2,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT2_DB, FETCH }, // BIT 2,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT2_DB, FETCH }, // BIT 2,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT2_DB, FETCH }, // BIT 2,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT2_DB, FETCH }, // BIT 2,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT2_DB, FETCH }, // BIT 2,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT2_DB, FETCH }, // BIT 2,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT3_DB, FETCH }, // BIT 3,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT3_DB, FETCH }, // BIT 3,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT3_DB, FETCH }, // BIT 3,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT3_DB, FETCH }, // BIT 3,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT3_DB, FETCH }, // BIT 3,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT3_DB, FETCH }, // BIT 3,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT3_DB, FETCH }, // BIT 3,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT3_DB, FETCH }, // BIT 3,(IX+d)

	// 0x60 - 0x6F
	{ NOP, READ, WAIT, NOP, BIT4_DB, FETCH }, // BIT 4,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT4_DB, FETCH }, // BIT 4,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT4_DB, FETCH }, // BIT 4,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT4_DB, FETCH }, // BIT 4,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT4_DB, FETCH }, // BIT 4,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT4_DB, FETCH }, // BIT 4,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT4_DB, FETCH }, // BIT 4,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT4_DB, FETCH }, // BIT 4,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT5_DB, FETCH }, // BIT 5,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT5_DB, FETCH }, // BIT 5,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT5_DB, FETCH }, // BIT 5,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT5_DB, FETCH }, // BIT 5,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT5_DB, FETCH }, // BIT 5,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT5_DB, FETCH }, // BIT 5,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT5_DB, FETCH }, // BIT 5,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT5_DB, FETCH }, // BIT 5,(IX+d)

	// 0x70 - 0x7F
	{ NOP, READ, WAIT, NOP, BIT6_DB, FETCH }, // BIT 6,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT6_DB, FETCH }, // BIT 6,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT6_DB, FETCH }, // BIT 6,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT6_DB, FETCH }, // BIT 6,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT6_DB, FETCH }, // BIT 6,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT6_DB, FETCH }, // BIT 6,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT6_DB, FETCH }, // BIT 6,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT6_DB, FETCH }, // BIT 6,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT7_DB, FETCH }, // BIT 7,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT7_DB, FETCH }, // BIT 7,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT7_DB, FETCH }, // BIT 7,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT7_DB, FETCH }, // BIT 7,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT7_DB, FETCH }, // BIT 7,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT7_DB, FETCH }, // BIT 7,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT7_DB, FETCH }, // BIT 7,(IX+d)
	{ NOP, READ, WAIT, NOP, BIT7_DB, FETCH }, // BIT 7,(IX+d)

	// 0x80 - 0x8F
	{ NOP, READ, WAIT, NOP, RES0_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // RES 0,(IX+d),B
	{ NOP, READ, WAIT, NOP, RES0_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // RES 0,(IX+d),C
	{ NOP, READ, WAIT, NOP, RES0_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // RES 0,(IX+d),D
	{ NOP, READ, WAIT, NOP, RES0_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // RES 0,(IX+d),E
	{ NOP, READ, WAIT, NOP, RES0_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // RES 0,(IX+d),H
	{ NOP, READ, WAIT, NOP, RES0_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // RES 0,(IX+d),L
	{ NOP, READ, WAIT, NOP, RES0_DB, WRITE_DB, WRITE, NOP, FETCH }, // RES 0,(IX+d)
	{ NOP, READ, WAIT, NOP, RES0_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // RES 0,(IX+d),A
	{ NOP, READ, WAIT, NOP, RES1_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // RES 1,(IX+d),B
	{ NOP, READ, WAIT, NOP, RES1_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // RES 1,(IX+d),C
	{ NOP, READ, WAIT, NOP, RES1_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // RES 1,(IX+d),D
	{ NOP, READ, WAIT, NOP, RES1_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // RES 1,(IX+d),E
	{ NOP, READ, WAIT, NOP, RES1_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // RES 1,(IX+d),H
	{ NOP, READ, WAIT, NOP, RES1_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // RES 1,(IX+d),L
	{ NOP, READ, WAIT, NOP, RES1_DB, WRITE_DB, WRITE, NOP, FETCH }, // RES 1,(IX+d)
	{ NOP, READ, WAIT, NOP, RES1_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // RES 1,(IX+d),A

	// 0x90 - 0x9F
	{ NOP, READ, WAIT, NOP, RES2_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // RES 2,(IX+d),B
	{ NOP, READ, WAIT, NOP, RES2_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // RES 2,(IX+d),C
	{ NOP, READ, WAIT, NOP, RES2_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // RES 2,(IX+d),D
	{ NOP, READ, WAIT, NOP, RES2_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // RES 2,(IX+d),E
	{ NOP, READ, WAIT, NOP, RES2_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // RES 2,(IX+d),H
	{ NOP, READ, WAIT, NOP, RES2_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // RES 2,(IX+d),L
	{ NOP, READ, WAIT, NOP, RES2_DB, WRITE_DB, WRITE, NOP, FETCH }, // RES 2,(IX+d)
	{ NOP, READ, WAIT, NOP, RES2_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // RES 2,(IX+d),A
	{ NOP, READ, WAIT, NOP, RES3_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // RES 3,(IX+d),B
	{ NOP, READ, WAIT, NOP, RES3_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // RES 3,(IX+d),C
	{ NOP, READ, WAIT, NOP, RES3_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // RES 3,(IX+d),D
	{ NOP, READ, WAIT, NOP, RES3_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // RES 3,(IX+d),E
	{ NOP, READ, WAIT, NOP, RES3_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // RES 3,(IX+d),H
	{ NOP, READ, WAIT, NOP, RES3_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // RES 3,(IX+d),L
	{ NOP, READ, WAIT, NOP, RES3_DB, WRITE_DB, WRITE, NOP, FETCH }, // RES 3,(IX+d)
	{ NOP, READ, WAIT, NOP, RES3_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // RES 3,(IX+d),A

	// 0xA0 - 0xAF
	{ NOP, READ, WAIT, NOP, RES4_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // RES 4,(IX+d),B
	{ NOP, READ, WAIT, NOP, RES4_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // RES 4,(IX+d),C
	{ NOP, READ, WAIT, NOP, RES4_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // RES 4,(IX+d),D
	{ NOP, READ, WAIT, NOP, RES4_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // RES 4,(IX+d),E
	{ NOP, READ, WAIT, NOP, RES4_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // RES 4,(IX+d),H
	{ NOP, READ, WAIT, NOP, RES4_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // RES 4,(IX+d),L
	{ NOP, READ, WAIT, NOP, RES4_DB, WRITE_DB, WRITE, NOP, FETCH }, // RES 4,(IX+d)
	{ NOP, READ, WAIT, NOP, RES4_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // RES 4,(IX+d),A
	{ NOP, READ, WAIT, NOP, RES5_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // RES 5,(IX+d),B
	{ NOP, READ, WAIT, NOP, RES5_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // RES 5,(IX+d),C
	{ NOP, READ, WAIT, NOP, RES5_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // RES 5,(IX+d),D
	{ NOP, READ, WAIT, NOP, RES5_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // RES 5,(IX+d),E
	{ NOP, READ, WAIT, NOP, RES5_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // RES 5,(IX+d),H
	{ NOP, READ, WAIT, NOP, RES5_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // RES 5,(IX+d),L
	{ NOP, READ, WAIT, NOP, RES5_DB, WRITE_DB, WRITE, NOP, FETCH }, // RES 5,(IX+d)
	{ NOP, READ, WAIT, NOP, RES5_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // RES 5,(IX+d),A

	// 0xB0 - 0xBF
	{ NOP, READ, WAIT, NOP, RES6_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // RES 6,(IX+d),B
	{ NOP, READ, WAIT, NOP, RES6_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // RES 6,(IX+d),C
	{ NOP, READ, WAIT, NOP, RES6_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // RES 6,(IX+d),D
	{ NOP, READ, WAIT, NOP, RES6_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // RES 6,(IX+d),E
	{ NOP, READ, WAIT, NOP, RES6_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // RES 6,(IX+d),H
	{ NOP, READ, WAIT, NOP, RES6_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // RES 6,(IX+d),L
	{ NOP, READ, WAIT, NOP, RES6_DB, WRITE_DB, WRITE, NOP, FETCH }, // RES 6,(IX+d)
	{ NOP, READ, WAIT, NOP, RES6_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // RES 6,(IX+d),A
	{ NOP, READ, WAIT, NOP, RES7_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // RES 7,(IX+d),B
	{ NOP, READ, WAIT, NOP, RES7_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // RES 7,(IX+d),C
	{ NOP, READ, WAIT, NOP, RES7_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // RES 7,(IX+d),D
	{ NOP, READ, WAIT, NOP, RES7_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // RES 7,(IX+d),E
	{ NOP, READ, WAIT, NOP, RES7_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // RES 7,(IX+d),H
	{ NOP, READ, WAIT, NOP, RES7_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // RES 7,(IX+d),L
	{ NOP, READ, WAIT, NOP, RES7_DB, WRITE_DB, WRITE, NOP, FETCH }, // RES 7,(IX+d)
	{ NOP, READ, WAIT, NOP, RES7_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // RES 7,(IX+d),A

	// 0xC0 - 0xCF
	{ NOP, READ, WAIT, NOP, SET0_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // SET 0,(IX+d),B
	{ NOP, READ, WAIT, NOP, SET0_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // SET 0,(IX+d),C
	{ NOP, READ, WAIT, NOP, SET0_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // SET 0,(IX+d),D
	{ NOP, READ, WAIT, NOP, SET0_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // SET 0,(IX+d),E
	{ NOP, READ, WAIT, NOP, SET0_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // SET 0,(IX+d),H
	{ NOP, READ, WAIT, NOP, SET0_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // SET 0,(IX+d),L
	{ NOP, READ, WAIT, NOP, SET0_DB, WRITE_DB, WRITE, NOP, FETCH }, // SET 0,(IX+d)
	{ NOP, READ, WAIT, NOP, SET0_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // SET 0,(IX+d),A
	{ NOP, READ, WAIT, NOP, SET1_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // SET 1,(IX+d),B
	{ NOP, READ, WAIT, NOP, SET1_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // SET 1,(IX+d),C
	{ NOP, READ, WAIT, NOP, SET1_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // SET 1,(IX+d),D
	{ NOP, READ, WAIT, NOP, SET1_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // SET 1,(IX+d),E
	{ NOP, READ, WAIT, NOP, SET1_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // SET 1,(IX+d),H
	{ NOP, READ, WAIT, NOP, SET1_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // SET 1,(IX+d),L
	{ NOP, READ, WAIT, NOP, SET1_DB, WRITE_DB, WRITE, NOP, FETCH }, // SET 1,(IX+d)
	{ NOP, READ, WAIT, NOP, SET1_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // SET 1,(IX+d),A

	// 0xD0 - 0xDF
	{ NOP, READ, WAIT, NOP, SET2_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // SET 2,(IX+d),B
	{ NOP, READ, WAIT, NOP, SET2_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // SET 2,(IX+d),C
	{ NOP, READ, WAIT, NOP, SET2_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // SET 2,(IX+d),D
	{ NOP, READ, WAIT, NOP, SET2_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // SET 2,(IX+d),E
	{ NOP, READ, WAIT, NOP, SET2_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // SET 2,(IX+d),H
	{ NOP, READ, WAIT, NOP, SET2_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // SET 2,(IX+d),L
	{ NOP, READ, WAIT, NOP, SET2_DB, WRITE_DB, WRITE, NOP, FETCH }, // SET 2,(IX+d)
	{ NOP, READ, WAIT, NOP, SET2_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // SET 2,(IX+d),A
	{ NOP, READ, WAIT, NOP, SET3_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // SET 3,(IX+d),B
	{ NOP, READ, WAIT, NOP, SET3_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // SET 3,(IX+d),C
	{ NOP, READ, WAIT, NOP, SET3_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // SET 3,(IX+d),D
	{ NOP, READ, WAIT, NOP, SET3_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // SET 3,(IX+d),E
	{ NOP, READ, WAIT, NOP, SET3_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // SET 3,(IX+d),H
	{ NOP, READ, WAIT, NOP, SET3_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // SET 3,(IX+d),L
	{ NOP, READ, WAIT, NOP, SET3_DB, WRITE_DB, WRITE, NOP, FETCH }, // SET 3,(IX+d)
	{ NOP, READ, WAIT, NOP, SET3_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // SET 3,(IX+d),A

	// 0xE0 - 0xEF
	{ NOP, READ, WAIT, NOP, SET4_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // SET 4,(IX+d),B
	{ NOP, READ, WAIT, NOP, SET4_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // SET 4,(IX+d),C
	{ NOP, READ, WAIT, NOP, SET4_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // SET 4,(IX+d),D
	{ NOP, READ, WAIT, NOP, SET4_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // SET 4,(IX+d),E
	{ NOP, READ, WAIT, NOP, SET4_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // SET 4,(IX+d),H
	{ NOP, READ, WAIT, NOP, SET4_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // SET 4,(IX+d),L
	{ NOP, READ, WAIT, NOP, SET4_DB, WRITE_DB, WRITE, NOP, FETCH }, // SET 4,(IX+d)
	{ NOP, READ, WAIT, NOP, SET4_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // SET 4,(IX+d),A
	{ NOP, READ, WAIT, NOP, SET5_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // SET 5,(IX+d),B
	{ NOP, READ, WAIT, NOP, SET5_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // SET 5,(IX+d),C
	{ NOP, READ, WAIT, NOP, SET5_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // SET 5,(IX+d),D
	{ NOP, READ, WAIT, NOP, SET5_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // SET 5,(IX+d),E
	{ NOP, READ, WAIT, NOP, SET5_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // SET 5,(IX+d),H
	{ NOP, READ, WAIT, NOP, SET5_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // SET 5,(IX+d),L
	{ NOP, READ, WAIT, NOP, SET5_DB, WRITE_DB, WRITE, NOP, FETCH }, // SET 5,(IX+d)
	{ NOP, READ, WAIT, NOP, SET5_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // SET 5,(IX+d),A

	// 0xF0 - 0xFF
	{ NOP, READ, WAIT, NOP, SET6_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // SET 6,(IX+d),B
	{ NOP, READ, WAIT, NOP, SET6_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // SET 6,(IX+d),C
	{ NOP, READ, WAIT, NOP, SET6_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // SET 6,(IX+d),D
	{ NOP, READ, WAIT, NOP, SET6_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // SET 6,(IX+d),E
	{ NOP, READ, WAIT, NOP, SET6_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // SET 6,(IX+d),H
	{ NOP, READ, WAIT, NOP, SET6_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // SET 6,(IX+d),L
	{ NOP, READ, WAIT, NOP, SET6_DB, WRITE_DB, WRITE, NOP, FETCH }, // SET 6,(IX+d)
	{ NOP, READ, WAIT, NOP, SET6_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // SET 6,(IX+d),A
	{ NOP, READ, WAIT, NOP, SET7_DB, WRITE_DB, WRITE, LD_DB_INTO_B, FETCH }, // SET 7,(IX+d),B
	{ NOP, READ, WAIT, NOP, SET7_DB, WRITE_DB, WRITE, LD_DB_INTO_C, FETCH }, // SET 7,(IX+d),C
	{ NOP, READ, WAIT, NOP, SET7_DB, WRITE_DB, WRITE, LD_DB_INTO_D, FETCH }, // SET 7,(IX+d),D
	{ NOP, READ, WAIT, NOP, SET7_DB, WRITE_DB, WRITE, LD_DB_INTO_E, FETCH }, // SET 7,(IX+d),E
	{ NOP, READ, WAIT, NOP, SET7_DB, WRITE_DB, WRITE, LD_DB_INTO_H, FETCH }, // SET 7,(IX+d),H
	{ NOP, READ, WAIT, NOP, SET7_DB, WRITE_DB, WRITE, LD_DB_INTO_L, FETCH }, // SET 7,(IX+d),L
	{ NOP, READ, WAIT, NOP, SET7_DB, WRITE_DB, WRITE, NOP, FETCH }, // SET 7,(IX+d)
	{ NOP, READ, WAIT, NOP, SET7_DB, WRITE_DB, WRITE, LD_DB_INTO_A, FETCH }, // SET 7,(IX+d),A
};